version: '3.8'
services:
  node:
    build:
      context: .
    ports:
      - 8000:8000
      - 9229:9229
    environment:
      # - CONNECTIONSTRING=mongodb://mongo:27017/yoda_notes
      - PORT=8000
    volumes:
      - ./:/code
    command: npm run debug
  # mongo:
  #   image: mongo:4.2.12
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb:/data/db
  #     - mongodb_config:/data/configdb
# volumes:
#   mongodb:
#   mongodb_config:
